import { useCallback, useMemo, useState } from "react";

import { Button } from "@/components/ui/button";

import { NewDataTable } from '@/components/data-table';
import { DataGridColumnHeader } from '@/components/data-grid-column-header';

import { Settings } from "lucide-react";

import AddUserAccessForm from "./AddUserAccessForm";

const dataRec = [
    {
        "npk": "123456789",
        "username": "hovsmtpng",
        "email": "bYt7j@example.com",
        "fullName": "Hovely Simatupang",
        "company": "Puninar Logistics",
        "workLocation": "Jakarta",
        "division": "Trucking Division",
        "department": "Trucking Operations",
        "position": "Head of System",
        "level": "Staff",
        "group": "Group Trucking",
        "role": "Super Admin",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "987654321",
        "username": "andiputra",
        "email": "andi.putra@example.com",
        "fullName": "Andi Putra",
        "company": "Puninar Logistics",
        "workLocation": "Bandung",
        "division": "Warehouse Division",
        "department": "Warehouse Management",
        "position": "Administrator",
        "level": "Non-Active",
        "group": "Group Warehouse",
        "role": "Admin",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [],
        "supplierGroupAssigned": [
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "456789123",
        "username": "sariwati",
        "email": "sariwati@example.com",
        "fullName": "Sari Wati",
        "company": "Puninar Logistics",
        "workLocation": "Jakarta",
        "division": "Finance Division",
        "department": "Accounting",
        "position": "Staff",
        "level": "Staff",
        "group": "Group Finance",
        "role": "User",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "112233445",
        "username": "budianto",
        "email": "budi.anto@example.com",
        "fullName": "Budi Anto",
        "company": "Puninar Logistics",
        "workLocation": "Surabaya",
        "division": "HR Division",
        "department": "Human Resources",
        "position": "Viewer",
        "level": "Suspended",
        "group": "Group HR",
        "role": "Viewer",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "223344556",
        "username": "mariaputri",
        "email": "maria.putri@example.com",
        "fullName": "Maria Putri",
        "company": "Puninar Logistics",
        "workLocation": "Jakarta",
        "division": "Logistics Division",
        "department": "Logistics Planning",
        "position": "Manager",
        "level": "Staff",
        "group": "Group Logistics",
        "role": "Manager",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "334455667",
        "username": "ferdinan",
        "email": "ferdi@example.com",
        "fullName": "Ferdinan Sitorus",
        "company": "Puninar Logistics",
        "workLocation": "Bandung",
        "division": "IT Division",
        "department": "System Development",
        "position": "Staff",
        "level": "Staff",
        "group": "Group IT",
        "role": "User",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "445566778",
        "username": "lisandri",
        "email": "lisa.andri@example.com",
        "fullName": "Lisa Andri",
        "company": "Puninar Logistics",
        "workLocation": "Jakarta",
        "division": "Trucking Division",
        "department": "Fleet Management",
        "position": "Administrator",
        "level": "Non-Active",
        "group": "Group Trucking",
        "role": "Admin",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "556677889",
        "username": "yusufadhi",
        "email": "yusuf.adhi@example.com",
        "fullName": "Yusuf Adhi",
        "company": "Puninar Logistics",
        "workLocation": "Surabaya",
        "division": "Warehouse Division",
        "department": "Inventory Control",
        "position": "Head of System",
        "level": "Staff",
        "group": "Group Warehouse",
        "role": "Super Admin",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "667788990",
        "username": "dianpratiwi",
        "email": "dian.pratiwi@example.com",
        "fullName": "Dian Pratiwi",
        "company": "Puninar Logistics",
        "workLocation": "Jakarta",
        "division": "Finance Division",
        "department": "Financial Planning",
        "position": "Manager",
        "level": "Staff",
        "group": "Group Finance",
        "role": "Manager",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    },
    {
        "npk": "778899001",
        "username": "hendrawan",
        "email": "hendra.wan@example.com",
        "fullName": "Hendra Wan",
        "company": "Puninar Logistics",
        "workLocation": "Bandung",
        "division": "IT Division",
        "department": "Infrastructure",
        "position": "Viewer",
        "level": "Suspended",
        "group": "Group IT",
        "role": "Viewer",
        "customerGroupAssigned": [
            {
                id: '1',
                customerName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
        ],
        "poolAssigned": [
            {
                id: '1',
                poolName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '12',
                poolName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
        "supplierGroupAssigned": [
            {
                id: '1',
                supplierName: 'Kathryn Campbell',
                availability: 'online',
                avatar: '1.png',
                status: 'approved',
                flag: '🇺🇸',
                email: 'kathryn@apple.com',
                company: 'Apple',
                role: 'CEO',
                joined: '2021-04-15',
                location: 'San Francisco, USA',
                balance: 5143.03,
            },
            {
                id: '10',
                supplierName: 'Michael Clark',
                availability: 'away',
                avatar: '10.png',
                status: 'pending',
                flag: '🇮🇹',
                email: 'michael@eni.it',
                company: 'ENI',
                role: 'Engineer',
                joined: '2023-02-11',
                location: 'Milan, Italy',
                balance: 5214.88,
            },
            {
                id: '11',
                supplierName: 'Ava Wilson',
                availability: 'busy',
                avatar: '11.png',
                status: 'approved',
                flag: '🇧🇷',
                email: 'ava@vale.br',
                company: 'Vale',
                role: 'Software Engineer',
                joined: '2022-12-01',
                location: 'Rio de Janeiro, Brazil',
                balance: 9421.5,
            },
            {
                id: '12',
                supplierName: 'David Young',
                availability: 'offline',
                avatar: '12.png',
                status: 'approved',
                flag: '🇮🇳',
                email: 'david@tata.in',
                company: 'Tata',
                role: 'Sales Manager',
                joined: '2020-03-27',
                location: 'Mumbai, India',
                balance: 4521.67,
            },
        ],
    }
]

const UserAccess = () => {
    const [pagination, setPagination] = useState({
        pageIndex: 0,
        pageSize: 5,
    })

    const columns = useMemo(() => [
        {
            accessorKey: "npk",
            id: "npk",
            header: ({ column }) => <DataGridColumnHeader title="NPK" visibility={true} column={column} />,
            enableSorting: true,
        },
        {
            accessorKey: "username",
            id: "username",
            header: ({ column }) => <DataGridColumnHeader title="Username" visibility={true} column={column} />,
            enableSorting: true,
            meta: { filter: "search" },
        },
        {
            accessorKey: "full_name",
            id: "full_name",
            header: ({ column }) => <DataGridColumnHeader title="Full Name" visibility={true} column={column} />,
            enableSorting: true,
            cell: ({ row }) => {
                const name = row.original.full_name;
                const email = row.original.email;
                return (
                    <>
                        <h4 className="font-medium">
                            {name}
                        </h4>
                        <h4 className="text-muted-foreground">
                            {email}
                        </h4>
                    </>
                )
            }
        },
        {
            accessorKey: "role",
            id: "role",
            header: ({ column }) => <DataGridColumnHeader title="Role" visibility={true} column={column} />,
            enableSorting: true,
        },
        {
            accessorKey: "group",
            id: "group",
            header: ({ column }) => <DataGridColumnHeader title="Group" visibility={true} column={column} />,
            enableSorting: true,
        },
        {
            accessorKey: "poolAssigned",
            id: "poolAssigned",
            header: ({ column }) => <DataGridColumnHeader title="Pool Assigned" visibility={true} column={column} />,
            enableSorting: true,
            cell: ({ row }) => {
                const pools = row.getValue("poolAssigned");
                if (!Array.isArray(pools) || pools.length === 0) return "-";
                return `${pools.length} Pool`;
            },
        },
        {
            accessorKey: "customerGroupAssigned",
            id: "customerGroupAssigned",
            header: ({ column }) => <DataGridColumnHeader title="Customer Assigned" visibility={true} column={column} />,
            enableSorting: true,
            cell: ({ row }) => {
                const customers = row.getValue("customerGroupAssigned");
                if (!Array.isArray(customers) || customers.length === 0) return "-";
                return `${customers.length} Customer`;
            },
            size: 200
        },
        {
            accessorKey: "supplierGroupAssigned",
            id: "supplierGroupAssigned",
            header: ({ column }) => <DataGridColumnHeader title="Supplier Assigned" visibility={true} column={column} />,
            enableSorting: true,
            cell: ({ row }) => {
                const suppliers = row.getValue("supplierGroupAssigned");
                if (!Array.isArray(suppliers) || suppliers.length === 0) return "-";
                return `${suppliers.length} Supplier`;
            },
            size: 200
        },
        {
            accessorKey: "act",
            id: "act",
            header: ({ column }) => <DataGridColumnHeader title="" visibility={true} column={column} />,
            enableSorting: false,
            enableHiding: false,
            size: 45,
            cell: ({ row }) => {
                return (
                    <div className="flex items-center justify-center">
                        <Button variant="outline" mode="icon" size="sm" onClick={() => handleOpen(row.original)}>
                            <Settings className="text-foreground h-4 w-4" />
                        </Button>
                    </div>
                )
            },
        }
    ])

    const [modalState, setModalState] = useState({
        isOpen: false,
        title: "",
        description: "",
        showCancelButton: false,
    })

    const [editedData, setEditedData] = useState({
        npk: "",
        username: "",
        email: "",
        fullName: "",
        company: "",
        workLocation: "",
        division: "",
        department: "",
        position: "",
        level: "",
        group: "",
        role: "",
        customerGroupAssigned: [],
        poolAssigned: [],
        supplierGroupAssigned: [],
    })

    const openModal = ({ title, description, showCancelButton, dataRow }) => {
        setEditedData(prev => ({
            ...prev,
            ...dataRow,
        }));

        setModalState({
            isOpen: true,
            title,
            description,
            showCancelButton,
        })

    }

    const closeModal = () => {
        setModalState((prev) => ({ ...prev, isOpen: false, showCancelButton: false }))
        setEditedData({
            npk: "",
            username: "",
            email: "",
            fullName: "",
            company: "",
            workLocation: "",
            division: "",
            department: "",
            position: "",
            level: "",
            group: "",
            role: "",
            customerGroupAssigned: [],
            poolAssigned: [],
            supplierGroupAssigned: []
        })
    }

    const handleChange = (e) => {
        const updated = {
            ...editedData,
            [e.target.name]: e.target.value,
        }
        setEditedData(updated)
    }

    const handleChangeDatatableTransfer = (data, type) => {
        setEditedData((old) => ({
            ...old,
            [type]: data,
        }));
    };


    const handleSave = useCallback(() => {
        console.log("Form Data:", editedData)
        // TODO: kirim ke API
        closeModal()
    }, [editedData, closeModal])

    const handleOpen = useCallback((data) => {
        openModal({
            title: "Edit User Access",
            // description: "Ini modal description",
            showCancelButton: true,
            dataRow: data
        })
    }, [])

    const [columnFilters, setColumnFilters] = useState([])
    const [searchQuery, setSearchQuery] = useState('');
    const [sorting, setSorting] = useState([{ id: 'subco', asc: true }]);

    return (
        <div className="p-2 space-y-2">
            {/* Header */}
            <div className="flex items-center justify-between">
                <h1 className="text-lg font-bold">User Access</h1>
            </div>

            {/* Table */}
            <NewDataTable
                columns={columns}
                data={dataRec}
                pagination={pagination}
                setPagination={setPagination}
                sorting={sorting}
                setSorting={setSorting}
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
                columnFilters={columnFilters}
                setColumnFilters={setColumnFilters}
                config={
                    {
                        pinning: {
                            left: ["npk"],
                            right: ["act"],
                        },
                        headerSticky: true,
                        columnsPinnable: true,
                        columnsResizable: true,
                        columnsMovable: false,
                        columnsVisibility: false,

                        showColumnsPinnable: false,

                        showTotalRows: true,
                        showRowPerPage: true,
                        showPageOf: true,
                        showPagination: true,
                    }
                }
            />
            <AddUserAccessForm
                editedData={editedData}
                modalState={modalState}
                handleChange={handleChange}
                handleChangeDatatableTransfer={handleChangeDatatableTransfer}
                closeModal={closeModal}
                handleSave={handleSave}
            />
        </div>
    );
};

export default UserAccess;
